### ISSUE TITLE
Error while rendering "section": template

### ISSUE THREAD

**Issue by nikitbobba** [shenoybr/hugo-goa#24]
FIXED

**Comment by fazilakhtar** [comment]
It's because you haven't defined the `## Main Menu` tag in your config.toml file.

If you don't want to have the main menu item you can override the template html for `index.html`. 

Your new index.html under layouts `<proj_name>/layouts/index.html` should look like this,
```
{{ partial "header.html" . }}

{{ partial "avatar.html" . }}

{{ partial "info.html" . }}

{{ partial "social.html" . }}

{{ partial "footer.html" . }}
```

Note that I removed `{{ partial "main_menu.html" . }}` from the index.html that is loaded from the template.

Let me know if this helps.
